language: cpp
compiler:
- gcc
env:
  matrix:
  - NODE_NVM_VERSION="0.10"
  global:
  - BUILD: '/tmp/fontnik-build'
  - PKG_CONFIG_PATH: '/tmp/fontnik-build/lib/pkgconfig'
  - secure: "ft3khHSWI62fgn5V8vMMwU5ZGadAV3Ch7OSF8UfRMT+w1WU+b3JvoscrDW/LQeGOmM6pZ4vfgISQU4DENKUkryyUxzugu4b4JgHgCWEfmaeYpmDQoexh79XgPvcOytUq4ARqQFTllUnGm8exxvloxrnVtMzTssHDqF0Dv+rNc40="
  - secure: "IbPFay7ztwHe6+Vb8CmpFQ9ML9wH6OTRsN3DfujU/5goQ/OLLMUXeQaZWG26v/U1WtkynzjmdGc7ZUU6LGqey2i3sraRh7LmwFacFyCLWt9jReEMCF1qb37MVakPm4ZiS5CH9aziPqD0ea3cnmJquXhFo0+lFW2VQxXWIZHvTlE="
before_install:
- export platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
- export PATH="$BUILD/bin:$PATH"
- if [[ "$platform" == "linux" ]]; then export CXX=g++-4.8; export CC=gcc-4.8; fi
- git clone https://github.com/creationix/nvm.git ../.nvm
- source ../.nvm/nvm.sh
- nvm install $NODE_NVM_VERSION
- nvm use $NODE_NVM_VERSION
- node --version
- npm --version
- ./deps/travis-build.sh
install:
- npm install --build-from-source
script:
- npm test
after_success:
- ./deps/travis-publish.sh

