language: node_js

node_js:
 - "0.10"

env:
  global:
  - BUILD: '/tmp/fontserver-build'
  - PKG_CONFIG_PATH: '/tmp/fontserver-build/lib/pkgconfig'


before_install:
 - sudo add-apt-repository --yes ppa:george-edison55/gcc4.7-precise
 - sudo apt-get update
 - sudo apt-get install -y gcc-4.7 gcc g++
 - mkdir -p $BUILD
 - ./deps/build_icu.sh
 - ./deps/build_protobuf.sh
 - ./deps/build_freetype.sh
 - ./deps/build_harfbuzz.sh
 - export PATH="$BUILD/bin:$PATH"
 - echo "PKG_CONFIG_PATH is set to $PKG_CONFIG_PATH"
 - ls /tmp/fontserver-build/lib/pkgconfig

script:
 - npm install
 - npm test

