language: node_js

node_js:
 - "0.10"

env:
  global:
  - BUILD: '/tmp/fontserver-build'
  - PKG_CONFIG_PATH: '/tmp/fontserver-build/lib/pkgconfig'
  - secure: 'odYEXvhqQCw5TCQIdiME4nsKDyly+Sc1CI1UfEi3xKtQcxntIWTGMLNOyop1W3f4kVhEOdqWgB9tKMulBBIlqBLOoOql5hbdLExdwmtk3j2E2I34wR7vf7VJk9WAvxk49uqRhIors98SKhBzvt3PVZCtq8gZEZDrEM/Zx8hsSAg='
  - secure: 'mGyR6Q0WPXw3ze1rLuX0ArCh1GMSsPax8njnZD/xKnXsZMjgWA/+o7RI9UtqDrO187i99c0OLjTFWFQHWatcB2t2JRFRQEB/lt5Mpb8LENSNWr3/RKQQv806gsM6sxtoYUQkeO//6IKf0ATjp1ot7lNqy5o83z2XehvGoMZytJg='

before_install:
 - ./deps/travis-build.sh

install:
 - npm install --build-from-source

script:
 - npm test

after_success:
 - ./deps/travis-publish.sh

